CREATE OR REPLACE TASK task_load_automatic_clustering_history_ins
--WAREHOUSE = &{l_target_wh}
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
AFTER &{l_target_db}.&{l_target_schema}.task_load_automatic_clustering_history_hst
WHEN SYSTEM$STREAM_HAS_DATA('automatic_clustering_history_stream')
AS
EXECUTE IMMEDIATE $$
BEGIN 
 ALTER SESSION SET TIMEZONE = 'Europe/London';

INSERT INTO SNO_CENTRAL_MONITORING_RAW_DB_DATA_REP.LANDING.AUTOMATIC_CLUSTERING_HISTORY (DW_EVENT_SHK,ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, START_TIME, END_TIME, CREDITS_USED, NUM_BYTES_RECLUSTERED, NUM_ROWS_RECLUSTERED, TABLE_ID, TABLE_NAME, SCHEMA_ID, SCHEMA_NAME, DATABASE_ID, DATABASE_NAME, DW_FILE_NAME, DW_FILE_ROW_NO, DW_LOAD_TS) 
            SELECT DW_EVENT_SHK,ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, START_TIME,
             END_TIME, CREDITS_USED, NUM_BYTES_RECLUSTERED, NUM_ROWS_RECLUSTERED, TABLE_ID, TABLE_NAME,
              SCHEMA_ID, SCHEMA_NAME, DATABASE_ID, DATABASE_NAME, DW_FILE_NAME, DW_FILE_ROW_NO, DW_LOAD_TS
               FROM &{l_target_db}.&{l_target_schema}.AUTOMATIC_CLUSTERING_HISTORY_STREAM;

END;
$$;

