use role &{l_entity_name}_sysadmin&{l_fr_suffix};

use database &{l_target_db};
use schema &{l_target_schema};
use warehouse &{l_target_wh};
;

CREATE OR REPLACE TASK task_load_QUERY_ACCELERATION_HISTORY_ins
--WAREHOUSE = &{l_target_wh}
USER_TASK_MANAGED_INITIAL_WAREHOUSE_SIZE = 'XSMALL'
AFTER &{l_target_db}.&{l_target_schema}.task_load_QUERY_ACCELERATION_HISTORY_hst
WHEN SYSTEM$STREAM_HAS_DATA('query_acceleration_history_stream')
AS
EXECUTE IMMEDIATE $$
BEGIN 
ALTER SESSION SET TIMEZONE = 'Europe/London';

INSERT INTO SNO_CENTRAL_MONITORING_RAW_DB_DATA_REP.LANDING.QUERY_ACCELERATION_HISTORY (DW_EVENT_SHK,ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME,
START_TIME, END_TIME, CREDITS_USED, WAREHOUSE_ID, WAREHOUSE_NAME, DW_FILE_NAME, DW_FILE_ROW_NO, DW_LOAD_TS) 

            SELECT DW_EVENT_SHK,ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, START_TIME,
             END_TIME, CREDITS_USED,WAREHOUSE_ID, WAREHOUSE_NAME, DW_FILE_NAME, DW_FILE_ROW_NO, DW_LOAD_TS
               FROM &{l_target_db}.&{l_target_schema}.QUERY_ACCELERATION_HISTORY_STREAM;

END;
$$;