-------------------------------------
--login_history --delta with changes inserted as new records
--*new 2 columns added in soruce view i.e RESOURCE_GROUP & TYPE*
-------------------------------------
select * from security.login_history_stg;
select * from security.login_history_history limit 100;
select count(*) from security.login_history_history;--734531
select MAX(EVENT_TIMESTAMP) from security.login_history_history; -- 2023-08-27 05:18:35.034 +0100
select count(*) from snowflake.account_usage.login_history where event_timestamp <= '2023-08-27 05:18:35.034 +0100';--734531

--stg to history comparison
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, EVENT_ID, EVENT_TIMESTAMP, EVENT_TYPE, USER_NAME, CLIENT_IP, REPORTED_CLIENT_TYPE, REPORTED_CLIENT_VERSION, FIRST_AUTHENTICATION_FACTOR, SECOND_AUTHENTICATION_FACTOR, IS_SUCCESS, ERROR_CODE, ERROR_MESSAGE, RELATED_EVENT_ID, CONNECTION
FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.LOGIN_HISTORY_STG
MINUS 
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, EVENT_ID, EVENT_TIMESTAMP, EVENT_TYPE, USER_NAME, CLIENT_IP, REPORTED_CLIENT_TYPE, REPORTED_CLIENT_VERSION, FIRST_AUTHENTICATION_FACTOR, SECOND_AUTHENTICATION_FACTOR, IS_SUCCESS, ERROR_CODE, ERROR_MESSAGE, RELATED_EVENT_ID, CONNECTION 
FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.LOGIN_HISTORY_HISTORY;

--history to stage comparison
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, EVENT_ID, EVENT_TIMESTAMP, EVENT_TYPE, USER_NAME, CLIENT_IP, REPORTED_CLIENT_TYPE, REPORTED_CLIENT_VERSION, FIRST_AUTHENTICATION_FACTOR, SECOND_AUTHENTICATION_FACTOR, IS_SUCCESS, ERROR_CODE, ERROR_MESSAGE, RELATED_EVENT_ID, CONNECTION 
FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.LOGIN_HISTORY_HISTORY
WHERE DW_LOAD_TS > CURRENT_DATE()
MINUS
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, EVENT_ID, EVENT_TIMESTAMP, EVENT_TYPE, USER_NAME, CLIENT_IP, REPORTED_CLIENT_TYPE, REPORTED_CLIENT_VERSION, FIRST_AUTHENTICATION_FACTOR, SECOND_AUTHENTICATION_FACTOR, IS_SUCCESS, ERROR_CODE, ERROR_MESSAGE, RELATED_EVENT_ID, CONNECTION
FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.LOGIN_HISTORY_STG
;

--source to history comparison
select EVENT_ID, EVENT_TIMESTAMP, EVENT_TYPE, USER_NAME, CLIENT_IP, REPORTED_CLIENT_TYPE, REPORTED_CLIENT_VERSION, FIRST_AUTHENTICATION_FACTOR, SECOND_AUTHENTICATION_FACTOR, IS_SUCCESS, ERROR_CODE, ERROR_MESSAGE, RELATED_EVENT_ID, CONNECTION
FROM snowflake.account_usage.login_history
where event_timestamp <= (SELECT MAX(EVENT_TIMESTAMP) FROM security.LOGIN_HISTORY_HISTORY)
MINUS 
select EVENT_ID, EVENT_TIMESTAMP, EVENT_TYPE, USER_NAME, CLIENT_IP, REPORTED_CLIENT_TYPE, REPORTED_CLIENT_VERSION, FIRST_AUTHENTICATION_FACTOR, SECOND_AUTHENTICATION_FACTOR, IS_SUCCESS, ERROR_CODE, ERROR_MESSAGE, RELATED_EVENT_ID, CONNECTION 
FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.LOGIN_HISTORY_HISTORY;

--history to source comparison

select EVENT_ID, EVENT_TIMESTAMP, EVENT_TYPE, USER_NAME, CLIENT_IP, REPORTED_CLIENT_TYPE, REPORTED_CLIENT_VERSION, FIRST_AUTHENTICATION_FACTOR, SECOND_AUTHENTICATION_FACTOR, IS_SUCCESS, ERROR_CODE, ERROR_MESSAGE, RELATED_EVENT_ID, CONNECTION 
FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.LOGIN_HISTORY_HISTORY
MINUS
select EVENT_ID, EVENT_TIMESTAMP, EVENT_TYPE, USER_NAME, CLIENT_IP, REPORTED_CLIENT_TYPE, REPORTED_CLIENT_VERSION, FIRST_AUTHENTICATION_FACTOR, SECOND_AUTHENTICATION_FACTOR, IS_SUCCESS, ERROR_CODE, ERROR_MESSAGE, RELATED_EVENT_ID, CONNECTION
FROM snowflake.account_usage.login_history
where event_timestamp <= (SELECT MAX(EVENT_TIMESTAMP) FROM security.LOGIN_HISTORY_HISTORY)
;