-------------------------------------
--PASSWORD_POLICIES 
--delta with changes inserted as new records
-------------------------------------
select * from snowflake.account_usage.password_policies;--5 records
select * from security.password_policy_stg;--1 rec
select * from security.password_policy_history;--5 rec

select * from security.password_policy_history where dw_load_ts>current_date() ;
select dw_load_ts, count(*) from security.password_policy_history group by 1;

--stg to history comparison
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, ID, NAME, SCHEMA_ID, SCHEMA, DATABASE_ID, DATABASE, OWNER, OWNER_ROLE_TYPE, PASSWORD_MIN_LENGTH, PASSWORD_MAX_LENGTH, PASSWORD_MIN_UPPER_CASE_CHARS, PASSWORD_MIN_LOWER_CASE_CHARS, PASSWORD_MIN_NUMERIC_CHARS, PASSWORD_MIN_SPECIAL_CHARS, PASSWORD_MAX_AGE_DAYS, PASSWORD_MAX_RETRIES, PASSWORD_LOCKOUT_TIME_MINS, COMMENT, CREATED, LAST_ALTERED, DELETED
from security.password_policy_stg
MINUS
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, ID, NAME, SCHEMA_ID, SCHEMA, DATABASE_ID, DATABASE, OWNER, OWNER_ROLE_TYPE, PASSWORD_MIN_LENGTH, PASSWORD_MAX_LENGTH, PASSWORD_MIN_UPPER_CASE_CHARS, PASSWORD_MIN_LOWER_CASE_CHARS, PASSWORD_MIN_NUMERIC_CHARS, PASSWORD_MIN_SPECIAL_CHARS, PASSWORD_MAX_AGE_DAYS, PASSWORD_MAX_RETRIES, PASSWORD_LOCKOUT_TIME_MINS, COMMENT, CREATED, LAST_ALTERED, DELETED
from security.password_policy_history;

--history to stg comparison (as data is loaded only once, stg has less records and showing as unmatched)
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, ID, NAME, SCHEMA_ID, SCHEMA, DATABASE_ID, DATABASE, OWNER, OWNER_ROLE_TYPE, PASSWORD_MIN_LENGTH, PASSWORD_MAX_LENGTH, PASSWORD_MIN_UPPER_CASE_CHARS, PASSWORD_MIN_LOWER_CASE_CHARS, PASSWORD_MIN_NUMERIC_CHARS, PASSWORD_MIN_SPECIAL_CHARS, PASSWORD_MAX_AGE_DAYS, PASSWORD_MAX_RETRIES, PASSWORD_LOCKOUT_TIME_MINS, COMMENT, CREATED, LAST_ALTERED, DELETED
from security.password_policy_history where DW_LOAD_TS = (SELECT MAX(DW_LOAD_TS) FROM security.password_policy_history)
minus
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, ID, NAME, SCHEMA_ID, SCHEMA, DATABASE_ID, DATABASE, OWNER, OWNER_ROLE_TYPE, PASSWORD_MIN_LENGTH, PASSWORD_MAX_LENGTH, PASSWORD_MIN_UPPER_CASE_CHARS, PASSWORD_MIN_LOWER_CASE_CHARS, PASSWORD_MIN_NUMERIC_CHARS, PASSWORD_MIN_SPECIAL_CHARS, PASSWORD_MAX_AGE_DAYS, PASSWORD_MAX_RETRIES, PASSWORD_LOCKOUT_TIME_MINS, COMMENT, CREATED, LAST_ALTERED, DELETED
from security.password_policy_stg;

--source to history comparison
select ID, NAME, SCHEMA_ID, SCHEMA, DATABASE_ID, DATABASE, OWNER, OWNER_ROLE_TYPE, PASSWORD_MIN_LENGTH, PASSWORD_MAX_LENGTH, PASSWORD_MIN_UPPER_CASE_CHARS, PASSWORD_MIN_LOWER_CASE_CHARS, PASSWORD_MIN_NUMERIC_CHARS, PASSWORD_MIN_SPECIAL_CHARS, PASSWORD_MAX_AGE_DAYS, PASSWORD_MAX_RETRIES, PASSWORD_LOCKOUT_TIME_MINS, COMMENT, CREATED, LAST_ALTERED, DELETED
from snowflake.account_usage.password_policies
MINUS
select ID, NAME, SCHEMA_ID, SCHEMA, DATABASE_ID, DATABASE, OWNER, OWNER_ROLE_TYPE, PASSWORD_MIN_LENGTH, PASSWORD_MAX_LENGTH, PASSWORD_MIN_UPPER_CASE_CHARS, PASSWORD_MIN_LOWER_CASE_CHARS, PASSWORD_MIN_NUMERIC_CHARS, PASSWORD_MIN_SPECIAL_CHARS, PASSWORD_MAX_AGE_DAYS, PASSWORD_MAX_RETRIES, PASSWORD_LOCKOUT_TIME_MINS, COMMENT, CREATED, LAST_ALTERED, DELETED
from security.password_policy_history 
where (ID, NAME, LAST_ALTERED) in (SELECT ID, NAME, MAX(LAST_ALTERED) FROM security.password_policy_history  group by 1,2 )
;

--history to source comparison
select ID, NAME, SCHEMA_ID, SCHEMA, DATABASE_ID, DATABASE, OWNER, OWNER_ROLE_TYPE, PASSWORD_MIN_LENGTH, PASSWORD_MAX_LENGTH, PASSWORD_MIN_UPPER_CASE_CHARS, PASSWORD_MIN_LOWER_CASE_CHARS, PASSWORD_MIN_NUMERIC_CHARS, PASSWORD_MIN_SPECIAL_CHARS, PASSWORD_MAX_AGE_DAYS, PASSWORD_MAX_RETRIES, PASSWORD_LOCKOUT_TIME_MINS, COMMENT, CREATED, LAST_ALTERED, DELETED
from security.password_policy_history 
where (ID, NAME, LAST_ALTERED) in (SELECT ID, NAME, MAX(LAST_ALTERED) FROM security.password_policy_history  group by 1,2 )
minus
select ID, NAME, SCHEMA_ID, SCHEMA, DATABASE_ID, DATABASE, OWNER, OWNER_ROLE_TYPE, PASSWORD_MIN_LENGTH, PASSWORD_MAX_LENGTH, PASSWORD_MIN_UPPER_CASE_CHARS, PASSWORD_MIN_LOWER_CASE_CHARS, PASSWORD_MIN_NUMERIC_CHARS, PASSWORD_MIN_SPECIAL_CHARS, PASSWORD_MAX_AGE_DAYS, PASSWORD_MAX_RETRIES, PASSWORD_LOCKOUT_TIME_MINS, COMMENT, CREATED, LAST_ALTERED, DELETED
from snowflake.account_usage.password_policies
;