-------------------------------------
--replication_databases 
-- scd type 2
-------------------------------------
select * from snowflake.information_schema.replication_databases; --8
select * from security.replication_databases_stg; --3
select * from security.replication_databases_history;

--check data load history
select effective_from, count(*) from security.replication_databases_history group by 1 order by 1 desc; --there are no changes. 


--stg to history comparison
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, REGION_GROUP, SNOWFLAKE_REGION, REPLICATION_ACCOUNT_NAME, DATABASE_NAME, COMMENT, CREATED, IS_PRIMARY, PRIMARY, REPLICATION_ALLOWED_TO_ACCOUNTS, FAILOVER_ALLOWED_TO_ACCOUNTS
from SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.REPLICATION_DATABASES_STG
MINUS
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, REGION_GROUP, SNOWFLAKE_REGION, REPLICATION_ACCOUNT_NAME, DATABASE_NAME, COMMENT, CREATED, IS_PRIMARY, PRIMARY, REPLICATION_ALLOWED_TO_ACCOUNTS, FAILOVER_ALLOWED_TO_ACCOUNTS
from SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.REPLICATION_DATABASES_HISTORY
where effective_to is null
;


--history to stage comparison
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, REGION_GROUP, SNOWFLAKE_REGION, REPLICATION_ACCOUNT_NAME, DATABASE_NAME, COMMENT, CREATED, IS_PRIMARY, PRIMARY, REPLICATION_ALLOWED_TO_ACCOUNTS, FAILOVER_ALLOWED_TO_ACCOUNTS
from SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.REPLICATION_DATABASES_HISTORY
where effective_to is null
MINUS
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, REGION_GROUP, SNOWFLAKE_REGION, REPLICATION_ACCOUNT_NAME, DATABASE_NAME, COMMENT, CREATED, IS_PRIMARY, PRIMARY, REPLICATION_ALLOWED_TO_ACCOUNTS, FAILOVER_ALLOWED_TO_ACCOUNTS
from SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.REPLICATION_DATABASES_STG
;

--source to history comparison
select REGION_GROUP, SNOWFLAKE_REGION, ACCOUNT_NAME, DATABASE_NAME, COMMENT, CREATED, IS_PRIMARY, PRIMARY, REPLICATION_ALLOWED_TO_ACCOUNTS, FAILOVER_ALLOWED_TO_ACCOUNTS
from SNOWFLAKE.INFORMATION_SCHEMA.REPLICATION_DATABASES
MINUS
select REGION_GROUP, SNOWFLAKE_REGION, REPLICATION_ACCOUNT_NAME, DATABASE_NAME, COMMENT, CREATED, IS_PRIMARY, PRIMARY, REPLICATION_ALLOWED_TO_ACCOUNTS, FAILOVER_ALLOWED_TO_ACCOUNTS
from SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.REPLICATION_DATABASES_HISTORY
where (REGION_GROUP, SNOWFLAKE_REGION, REPLICATION_ACCOUNT_NAME, DATABASE_NAME, EFFECTIVE_FROM)
  IN (SELECT REGION_GROUP, SNOWFLAKE_REGION, REPLICATION_ACCOUNT_NAME, DATABASE_NAME, MAX(EFFECTIVE_FROM) FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.REPLICATION_DATABASES_HISTORY group by 1,2,3,4)
;

--history to source comparison
select REGION_GROUP, SNOWFLAKE_REGION, REPLICATION_ACCOUNT_NAME, DATABASE_NAME, COMMENT, CREATED, IS_PRIMARY, PRIMARY, REPLICATION_ALLOWED_TO_ACCOUNTS, FAILOVER_ALLOWED_TO_ACCOUNTS
from SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.REPLICATION_DATABASES_HISTORY
where (REGION_GROUP, SNOWFLAKE_REGION, REPLICATION_ACCOUNT_NAME, DATABASE_NAME, EFFECTIVE_FROM)
  IN (SELECT REGION_GROUP, SNOWFLAKE_REGION, REPLICATION_ACCOUNT_NAME, DATABASE_NAME, MAX(EFFECTIVE_FROM) FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.REPLICATION_DATABASES_HISTORY group by 1,2,3,4)
MINUS
select REGION_GROUP, SNOWFLAKE_REGION, ACCOUNT_NAME, DATABASE_NAME, COMMENT, CREATED, IS_PRIMARY, PRIMARY, REPLICATION_ALLOWED_TO_ACCOUNTS, FAILOVER_ALLOWED_TO_ACCOUNTS
from SNOWFLAKE.INFORMATION_SCHEMA.REPLICATION_DATABASES;

--update 1 record manually to check
UPDATE SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.REPLICATION_DATABASES_HISTORY SET COMMENT='Testing SCD Type 2'
WHERE REPLICATION_ACCOUNT_NAME = 'SNOLSELZPROD';

--Re-run to validate scd type 2 changes

--check data load history
select effective_from, count(*) from security.replication_databases_history group by 1 order by 1 desc; --Changes found after manual data updation

select * from security.replication_databases_history where effective_from >= '2023-06-28 12:15:21.786 +0100';

select * from security.replication_databases_history where replication_account_name='SNOLSELZPROD';