-------------------------------------
--Tables 
--Daily snap
-------------------------------------
Select * from snowflake.account_usage.tables;--2560 rows
select * from security.tables_history;--66.3k
select dw_load_ts, count(*) from security.tables_history group by 1 order by 1 desc; --2560 for current date

--source to history comparison (with row count, bytes & last altered as they keep changing)
select TABLE_ID, TABLE_NAME, TABLE_SCHEMA_ID, TABLE_SCHEMA, TABLE_CATALOG_ID, TABLE_CATALOG, TABLE_OWNER, TABLE_TYPE, IS_TRANSIENT, CLUSTERING_KEY
--, ROW_COUNT, BYTES, LAST_ALTERED
, RETENTION_TIME, SELF_REFERENCING_COLUMN_NAME, REFERENCE_GENERATION, USER_DEFINED_TYPE_CATALOG, USER_DEFINED_TYPE_SCHEMA, USER_DEFINED_TYPE_NAME, IS_INSERTABLE_INTO, IS_TYPED, COMMIT_ACTION, CREATED, DELETED, AUTO_CLUSTERING_ON, COMMENT
from snowflake.account_usage.tables
minus
select TABLE_ID, TABLE_NAME, TABLE_SCHEMA_ID, TABLE_SCHEMA, TABLE_CATALOG_ID, TABLE_CATALOG, TABLE_OWNER, TABLE_TYPE, IS_TRANSIENT, CLUSTERING_KEY
--, ROW_COUNT, BYTES, LAST_ALTERED
, RETENTION_TIME, SELF_REFERENCING_COLUMN_NAME, REFERENCE_GENERATION, USER_DEFINED_TYPE_CATALOG, USER_DEFINED_TYPE_SCHEMA, USER_DEFINED_TYPE_NAME, IS_INSERTABLE_INTO, IS_TYPED, COMMIT_ACTION, CREATED, DELETED, AUTO_CLUSTERING_ON, COMMENT
from security.tables_history where dw_load_ts > current_date();

--history to source comparison (with row count, bytes & last altered as they keep changing)
select TABLE_ID, TABLE_NAME, TABLE_SCHEMA_ID, TABLE_SCHEMA, TABLE_CATALOG_ID, TABLE_CATALOG, TABLE_OWNER, TABLE_TYPE, IS_TRANSIENT, CLUSTERING_KEY
--, ROW_COUNT, BYTES, LAST_ALTERED
, RETENTION_TIME, SELF_REFERENCING_COLUMN_NAME, REFERENCE_GENERATION, USER_DEFINED_TYPE_CATALOG, USER_DEFINED_TYPE_SCHEMA, USER_DEFINED_TYPE_NAME, IS_INSERTABLE_INTO, IS_TYPED, COMMIT_ACTION, CREATED, DELETED, AUTO_CLUSTERING_ON, COMMENT
from security.tables_history where dw_load_ts > current_date()
minus
select TABLE_ID, TABLE_NAME, TABLE_SCHEMA_ID, TABLE_SCHEMA, TABLE_CATALOG_ID, TABLE_CATALOG, TABLE_OWNER, TABLE_TYPE, IS_TRANSIENT, CLUSTERING_KEY
--, ROW_COUNT, BYTES, LAST_ALTERED
, RETENTION_TIME, SELF_REFERENCING_COLUMN_NAME, REFERENCE_GENERATION, USER_DEFINED_TYPE_CATALOG, USER_DEFINED_TYPE_SCHEMA, USER_DEFINED_TYPE_NAME, IS_INSERTABLE_INTO, IS_TYPED, COMMIT_ACTION, CREATED, DELETED, AUTO_CLUSTERING_ON, COMMENT
from snowflake.account_usage.tables
;

-- just to check if non-compared fields are being populated
select count(*) from security.tables_history where ROW_COUNT is null or BYTES is null or LAST_ALTERED is null;