
-------------------------------------
--users -- scd type 2 
--
-------------------------------------
select * from snowflake.account_usage.users; --36
select * from security.users_stg; --36
select * from security.users_history; --80 records

select effective_from, count(*) from security.users_history group by 1 order by 1 desc; -- check data load history by date
select * from security.users_history where effective_from > current_date();

--stage to history comparison
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, NAME, CREATED_ON, DELETED_ON, LOGIN_NAME, DISPLAY_NAME, FIRST_NAME, LAST_NAME, EMAIL, MUST_CHANGE_PASSWORD, HAS_PASSWORD, COMMENT, DISABLED, SNOWFLAKE_LOCK, DEFAULT_WAREHOUSE, DEFAULT_NAMESPACE, DEFAULT_ROLE, EXT_AUTHN_DUO, EXT_AUTHN_UID, BYPASS_MFA_UNTIL, LAST_SUCCESS_LOGIN, EXPIRES_AT, LOCKED_UNTIL_TIME, HAS_RSA_PUBLIC_KEY, PASSWORD_LAST_SET_TIME, OWNER, DEFAULT_SECONDARY_ROLE
FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.USERS_STG
MINUS
SELECT ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, NAME, CREATED_ON, DELETED_ON, LOGIN_NAME, DISPLAY_NAME, FIRST_NAME, LAST_NAME, EMAIL, MUST_CHANGE_PASSWORD, HAS_PASSWORD, COMMENT, DISABLED, SNOWFLAKE_LOCK, DEFAULT_WAREHOUSE, DEFAULT_NAMESPACE, DEFAULT_ROLE, EXT_AUTHN_DUO, EXT_AUTHN_UID, BYPASS_MFA_UNTIL, LAST_SUCCESS_LOGIN, EXPIRES_AT, LOCKED_UNTIL_TIME, HAS_RSA_PUBLIC_KEY, PASSWORD_LAST_SET_TIME, OWNER, DEFAULT_SECONDARY_ROLE
FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.USERS_HISTORY;

--history to stage comparison
SELECT ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, NAME, CREATED_ON, DELETED_ON, LOGIN_NAME, DISPLAY_NAME, FIRST_NAME, LAST_NAME, EMAIL, MUST_CHANGE_PASSWORD, HAS_PASSWORD, COMMENT, DISABLED, SNOWFLAKE_LOCK, DEFAULT_WAREHOUSE, DEFAULT_NAMESPACE, DEFAULT_ROLE, EXT_AUTHN_DUO, EXT_AUTHN_UID, BYPASS_MFA_UNTIL, LAST_SUCCESS_LOGIN, EXPIRES_AT, LOCKED_UNTIL_TIME, HAS_RSA_PUBLIC_KEY, PASSWORD_LAST_SET_TIME, OWNER, DEFAULT_SECONDARY_ROLE
FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.USERS_HISTORY 
WHERE (NAME, CREATED_ON, NVL(DELETED_ON,'2021-01-01'), LOGIN_NAME, NVL(DISPLAY_NAME,''), NVL(FIRST_NAME,''), NVL(LAST_NAME,''), NVL(EMAIL,''), EFFECTIVE_FROM)  
 IN (select NAME, CREATED_ON, NVL(DELETED_ON,'2021-01-01'), LOGIN_NAME, NVL(DISPLAY_NAME,''), NVL(FIRST_NAME,''), NVL(LAST_NAME,''), NVL(EMAIL,''), MAX(EFFECTIVE_FROM)
     FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.USERS_HISTORY GROUP BY 1,2,3,4,5,6,7,8)
MINUS
select ORGANIZATION_NAME, ACCOUNT_NAME, REGION_NAME, NAME, CREATED_ON, DELETED_ON, LOGIN_NAME, DISPLAY_NAME, FIRST_NAME, LAST_NAME, EMAIL, MUST_CHANGE_PASSWORD, HAS_PASSWORD, COMMENT, DISABLED, SNOWFLAKE_LOCK, DEFAULT_WAREHOUSE, DEFAULT_NAMESPACE, DEFAULT_ROLE, EXT_AUTHN_DUO, EXT_AUTHN_UID, BYPASS_MFA_UNTIL, LAST_SUCCESS_LOGIN, EXPIRES_AT, LOCKED_UNTIL_TIME, HAS_RSA_PUBLIC_KEY, PASSWORD_LAST_SET_TIME, OWNER, DEFAULT_SECONDARY_ROLE
FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.USERS_STG;

--source to history comparison (removed LAST_SUCCESS_LOGIN from comparison as it keeps changing)
select NAME, CREATED_ON, DELETED_ON, LOGIN_NAME, DISPLAY_NAME, FIRST_NAME, LAST_NAME, EMAIL, MUST_CHANGE_PASSWORD, HAS_PASSWORD, COMMENT, DISABLED, SNOWFLAKE_LOCK, DEFAULT_WAREHOUSE, DEFAULT_NAMESPACE, DEFAULT_ROLE, EXT_AUTHN_DUO, EXT_AUTHN_UID, BYPASS_MFA_UNTIL, EXPIRES_AT, LOCKED_UNTIL_TIME, HAS_RSA_PUBLIC_KEY, PASSWORD_LAST_SET_TIME, OWNER, DEFAULT_SECONDARY_ROLE
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS
MINUS
SELECT NAME, CREATED_ON, DELETED_ON, LOGIN_NAME, DISPLAY_NAME, FIRST_NAME, LAST_NAME, EMAIL, MUST_CHANGE_PASSWORD, HAS_PASSWORD, COMMENT, DISABLED, SNOWFLAKE_LOCK, DEFAULT_WAREHOUSE, DEFAULT_NAMESPACE, DEFAULT_ROLE, EXT_AUTHN_DUO, EXT_AUTHN_UID, BYPASS_MFA_UNTIL, EXPIRES_AT, LOCKED_UNTIL_TIME, HAS_RSA_PUBLIC_KEY, PASSWORD_LAST_SET_TIME, OWNER, DEFAULT_SECONDARY_ROLE
FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.USERS_HISTORY;

--history to source comparison (removed LAST_SUCCESS_LOGIN from comparison as it keeps changing)
SELECT NAME, CREATED_ON, DELETED_ON, LOGIN_NAME, DISPLAY_NAME, FIRST_NAME, LAST_NAME, EMAIL, MUST_CHANGE_PASSWORD, HAS_PASSWORD, COMMENT, DISABLED, SNOWFLAKE_LOCK, DEFAULT_WAREHOUSE, DEFAULT_NAMESPACE, DEFAULT_ROLE, EXT_AUTHN_DUO, EXT_AUTHN_UID, BYPASS_MFA_UNTIL, EXPIRES_AT, LOCKED_UNTIL_TIME, HAS_RSA_PUBLIC_KEY, PASSWORD_LAST_SET_TIME, OWNER, DEFAULT_SECONDARY_ROLE
FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.USERS_HISTORY
WHERE (NAME, CREATED_ON, NVL(DELETED_ON,'2021-01-01'), LOGIN_NAME, NVL(DISPLAY_NAME,''), NVL(FIRST_NAME,''), NVL(LAST_NAME,''), NVL(EMAIL,''), EFFECTIVE_FROM)  
 IN (select NAME, CREATED_ON, NVL(DELETED_ON,'2021-01-01'), LOGIN_NAME, NVL(DISPLAY_NAME,''), NVL(FIRST_NAME,''), NVL(LAST_NAME,''), NVL(EMAIL,''), MAX(EFFECTIVE_FROM)
     FROM SNO_CENTRAL_MONITORING_RAW_DB.SECURITY.USERS_HISTORY GROUP BY 1,2,3,4,5,6,7,8)
MINUS
select NAME, CREATED_ON, DELETED_ON, LOGIN_NAME, DISPLAY_NAME, FIRST_NAME, LAST_NAME, EMAIL, MUST_CHANGE_PASSWORD, HAS_PASSWORD, COMMENT, DISABLED, SNOWFLAKE_LOCK, DEFAULT_WAREHOUSE, DEFAULT_NAMESPACE, DEFAULT_ROLE, EXT_AUTHN_DUO, EXT_AUTHN_UID, BYPASS_MFA_UNTIL, EXPIRES_AT, LOCKED_UNTIL_TIME, HAS_RSA_PUBLIC_KEY, PASSWORD_LAST_SET_TIME, OWNER, DEFAULT_SECONDARY_ROLE
FROM SNOWFLAKE.ACCOUNT_USAGE.USERS
;